Class {
	#name : #GtAlgorithmerBlockVisitor,
	#superclass : #Object,
	#category : #'GToolkit-Algorithmer-Visitor'
}

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitAlgorithmer: anAlgorithmer [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitAssignVariableBlock: anAssignVariableBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitDefineVariableBlock: aDefineVariableBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitIfBlock: anIfBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitMessageSendBlock: aMessageSendBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitOperatorBlock: anOperatorBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitPrintlnBlock: aPrintlnBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitPushHeapBlock: aPushHeapBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitSequenceBlock: aSequenceBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitVariableBlock: aVariableBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitWhileBlock: aWhileBlock [
]
